// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF7_x8mKRghTb15ebH_czqm5bEyTE5RS0',
    appId: '1:376137208953:web:85025bbd9afaef66e530a8',
    messagingSenderId: '376137208953',
    projectId: 'auth-phase-1',
    authDomain: 'auth-phase-1.firebaseapp.com',
    storageBucket: 'auth-phase-1.firebasestorage.app',
    measurementId: 'G-NQXJ3GCF54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiBIWXTPENkcStcmAU_N3JqgqgoWXEuhw',
    appId: '1:376137208953:android:a9413cdf45f87fdae530a8',
    messagingSenderId: '376137208953',
    projectId: 'auth-phase-1',
    storageBucket: 'auth-phase-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD55BS8tQk7fBJZfFhdG4p4GHVHBaUU4lM',
    appId: '1:376137208953:ios:b8f960e061cc476fe530a8',
    messagingSenderId: '376137208953',
    projectId: 'auth-phase-1',
    storageBucket: 'auth-phase-1.firebasestorage.app',
    iosBundleId: 'com.example.authProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD55BS8tQk7fBJZfFhdG4p4GHVHBaUU4lM',
    appId: '1:376137208953:ios:b8f960e061cc476fe530a8',
    messagingSenderId: '376137208953',
    projectId: 'auth-phase-1',
    storageBucket: 'auth-phase-1.firebasestorage.app',
    iosBundleId: 'com.example.authProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF7_x8mKRghTb15ebH_czqm5bEyTE5RS0',
    appId: '1:376137208953:web:67e8116241b02f97e530a8',
    messagingSenderId: '376137208953',
    projectId: 'auth-phase-1',
    authDomain: 'auth-phase-1.firebaseapp.com',
    storageBucket: 'auth-phase-1.firebasestorage.app',
    measurementId: 'G-1BQ4TX3NJ6',
  );
}
